### ISSUE TITLE
Drop Rcss prefix

### ISSUE THREAD

**Issue by nfultz** [tkonopka/Rcssplot#10]
Currently, all wrappers start in an Rcss prefix; probably to avoid accidental infinite recursion. It would be easier to use if it's just `plot` instead of `Rcssplot`; since this package will be attached after `graphics` we can just mask the `plot` function instead.

**Comment by tkonopka** [comment]
In principle, it should be possible to overload the usual functions, i.e. name the new functions plot() etc. and avoid the "Rcss" prefixes. Calls to the original plot functions would then have to change from "plot()" to "graphics::plot()" in order to avoid recursion.

However, I would like to be sure that the Rcssplot implementation is really mature before changing such basic R functionality as plots. 

For now, with the prefixes, one is sure that older code written using base graphics will always execute as intended.
